import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [horoscope, setHoroscope] = useState("");
  const [recommendations, setRecommendations] = useState([]);
  const zodiacSign = "libra";

  useEffect(() => {
    fetchHoroscope();
    fetchSpotify()
  }, []);

  const fetchHoroscope = async () => {
    try {
      console.log("start here");

      const res = await fetch('/api/horoscope');
      console.log("Fetch res: ", res);
      if (!res.ok) {
        throw new Error("Response was not ok");
      }
      const data = await res.json();
      console.log("Horo data", data)
      setHoroscope(data.horoscope);
      console.log(setHoroscope);
    } catch (error) {
      console.error("Horoscope Error: ", error);
      setHoroscope("Failed to fetch horoscope");
    }
  };

  const fetchSpotify = async () => {
    try {
      console.log("Staring spotify part")
      const response = await fetch('/api/spotify')

      console.log("Response:", response)
      if (!response.ok) {
        throw new Error('Response was not ok')
      }
      const data = await response.json()
      console.log("Data: ", data)
      setRecommendations(data.tracks)
    } catch (error) {
      console.error("Error fetching Spotify", error);
      setRecommendations([]);
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <div>
          <h1>Horoscope and Spotify Intergration</h1>
          <div>
            <h2>Daily Horoscope</h2>
            <p>{horoscope || "Loading horoscope.."}</p>
          </div>
          <div>
            <h2>Spotify Reccomendations</h2>
            {recommendations.length > 0 ? (
              <ul>
                {recommendations.map((track) => (
                  <li key={track.id}>
                    <a
                      href={track.external_urls.spotify}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {track.name}
                    </a>
                  </li>
                ))}
              </ul>
            ) : (
              <p> Loading recs..</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
